/**
 * 演示数据（P1 强化学习域）：复习中心、情境练习场、技能雷达、个人资料库、内容运营台。
 */
import type {
  MemoryCard,
  Scenario,
  ScenarioSession,
  ScenarioReport,
  SkillDimension,
  LibraryItem,
  ResourceFlag,
  CurriculumRelease,
  SourceDomainRule,
} from "@/lib/types";

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
const inDays = (n: number) => new Date(Date.now() + n * 86400000).toISOString();

/* ---------------- 复习中心 ---------------- */

export const MEMORY_CARDS: MemoryCard[] = [
  {
    id: "card-01",
    nodeId: "need-signal",
    front: "为什么「用户说想要深色模式」不能直接写成需求？",
    backSummary: "区分表象诉求、场景、痛点与可验证假设；先澄清任务与证据。",
    sourceKind: "node",
    sourceTitle: "产品经理教材 · 需求分析 2.3",
    tags: ["需求分析"],
    dueAt: inDays(0),
    intervalDays: 2,
    easeFactor: 2.5,
    status: "due",
  },
  {
    id: "card-02",
    nodeId: "need-signal",
    front: "一条可验证需求假设通常包含哪几个要素？",
    backSummary: "目标用户、场景/动机、期望行为、可量化成功标准。",
    sourceKind: "practice_gap",
    sourceTitle: "费曼练习待补：可验证假设的成功标准",
    tags: ["需求分析"],
    dueAt: inDays(0),
    intervalDays: 1,
    easeFactor: 2.2,
    status: "due",
  },
  {
    id: "card-03",
    nodeId: "user-research-basics",
    front: "如何避免访谈中的诱导性问题？",
    backSummary: "用开放问题与具体情境，请用户描述行为而非评价方案。",
    sourceKind: "node",
    sourceTitle: "产品经理教材 · 用户研究 2.5",
    tags: ["需求分析"],
    dueAt: inDays(0),
    intervalDays: 3,
    easeFactor: 2.6,
    status: "due",
  },
  {
    id: "card-04",
    nodeId: "pm-mindset",
    front: "问题先于方案的含义是什么？",
    backSummary: "在讨论怎么做之前，先确认要解决谁的什么问题与约束。",
    sourceKind: "node",
    sourceTitle: "产品经理教材 · 产品思维 1.2",
    tags: ["产品思维"],
    dueAt: inDays(0),
    intervalDays: 4,
    easeFactor: 2.8,
    status: "due",
  },
  {
    id: "card-05",
    nodeId: "prd-structure",
    front: "PRD 的问题定义章节通常写什么？",
    backSummary: "背景、目标用户、当前痛点、目标与成功指标。",
    sourceKind: "node",
    sourceTitle: "产品经理教材 · PRD 5.1",
    tags: ["PRD"],
    dueAt: inDays(1),
    intervalDays: 5,
    easeFactor: 2.7,
    status: "scheduled",
  },
  {
    id: "card-06",
    nodeId: "need-signal",
    front: "验证假设失败后应该做什么？",
    backSummary: "回看基线数据，判断是假设问题、验证方式问题还是范围问题，再迭代。",
    sourceKind: "practice_gap",
    sourceTitle: "费曼练习待补：验证失败的回退判断",
    tags: ["需求分析"],
    dueAt: inDays(0),
    intervalDays: 2,
    easeFactor: 2.1,
    status: "due",
  },
];

export const REVIEW_DUE_CARDS = MEMORY_CARDS.filter((c) => c.status === "due");

/* ---------------- 情境练习场 ---------------- */

export const SCENARIOS: Scenario[] = [
  {
    id: "scenario-renewal",
    title: "会员续费下降：第一次需求澄清会",
    summary: "连续两周续费率下降 8%，增长负责人要求本周上线「续费弹窗」。",
    persona: "增长负责人林岚",
    personaRole: "业务方",
    skillTags: ["需求分析", "需求澄清"],
    difficulty: "初级",
    estimatedMinutes: 15,
    sourceNodeId: "need-signal",
    competencyId: "comp-need",
    task: "在承诺方案之前，先澄清用户、漏斗、基线数据与约束。",
    goal: "识别表象诉求（弹窗）并提出至少 3 类可验证问题：用户 / 指标基线 / 约束。",
    completionCriteria: [
      "至少提出 3 类有效澄清问题",
      "不急于承诺「上线弹窗」方案",
      "给出下一步验证计划",
    ],
    openingLine: "续费这周又降了 8%，你们今天能给方案吗？团队已经让先做续费弹窗了。",
    scenarioVersion: "v1.0",
    auxiliaryDocs: [
      { label: "漏斗摘要（虚构）", content: "注册→首单→次月续费：续费率连续两周下降；退订页无埋点数据。", isFictional: true },
      { label: "用户反馈摘录（脱敏）", content: "“到期忘了，邮件被当垃圾邮件。” “价格没变，但忘了是自动续费。”", isFictional: true },
    ],
    status: "published",
  },
  {
    id: "scenario-priority",
    title: "向研发解释优先级",
    summary: "资源有限，研发要求砍掉两个需求；你需要解释优先级取舍与证据。",
    persona: "研发负责人阿凯",
    personaRole: "研发",
    skillTags: ["PRD", "优先级"],
    difficulty: "中级",
    estimatedMinutes: 20,
    sourceNodeId: "prd-structure",
    competencyId: "comp-prd",
    task: "用影响、成本与证据解释优先级，而不是用职位压人。",
    goal: "把优先级决策讲成「影响 × 成本 × 风险」的可解释判断。",
    completionCriteria: ["给出两候选的对比口径", "承认不确定性并给出回退方案", "达成下一步共识"],
    openingLine: "排期只能做两个需求，你们每个都说是 P0，那按什么标准砍？",
    scenarioVersion: "v1.0",
    auxiliaryDocs: [
      { label: "需求清单（虚构）", content: "A：导出筛选结果（影响：周报场景高频）｜B：深色模式（影响：视觉偏好）｜C：批量标签（影响：运营效率）", isFictional: true },
    ],
    status: "published",
  },
  {
    id: "scenario-wireframe",
    title: "原型评审：与设计沟通",
    summary: "设计稿与低保真原型差异较大，需要澄清关键路径取舍。",
    persona: "设计师小禾",
    personaRole: "设计",
    skillTags: ["原型", "用户体验"],
    difficulty: "初级",
    estimatedMinutes: 15,
    sourceNodeId: "wireframe-ux",
    competencyId: "comp-prototype",
    task: "围绕关键路径与可用性目标对齐原型差异。",
    goal: "用关键路径与可用性原则解释设计取舍。",
    completionCriteria: ["指出 1 处需要保底的关键路径", "把分歧转为可验证的取舍"],
    openingLine: "这个列表页我觉得可以改成一屏大图，你看呢？",
    scenarioVersion: "v1.0",
    auxiliaryDocs: [{ label: "低保真原型说明（虚构）", content: "关键路径：筛选 → 结果列表 → 详情 → 导出。", isFictional: true }],
    status: "published",
  },
  {
    id: "scenario-clear-request",
    title: "向业务方澄清模糊需求",
    summary: "业务方一句话需求，需要拆解为可验证的问题。",
    persona: "业务负责人老王",
    personaRole: "业务方",
    skillTags: ["需求澄清"],
    difficulty: "初级",
    estimatedMinutes: 10,
    sourceNodeId: "need-signal",
    competencyId: "comp-need",
    task: "把「做一个会员体系」拆成用户、场景、指标问题。",
    goal: "识别表象诉求并给出澄清问题清单。",
    completionCriteria: ["至少 3 个澄清问题", "明确成功指标"],
    openingLine: "我们想做个会员体系，你们评估下要多久。",
    scenarioVersion: "v1.0",
    auxiliaryDocs: [{ label: "背景（虚构）", content: "目前无积分、无等级；客服反馈老用户活跃下滑。", isFictional: true }],
    status: "published",
  },
];

export const SCENARIO_REPORT: ScenarioReport = {
  id: "report-priority-01",
  achieved: [
    { claim: "用「影响 × 成本 × 风险」给出排序口径", messageIds: ["p3"] },
    { claim: "承认导出数据的不确定性并给出基线验证方案", messageIds: ["p5"] },
    { claim: "把分歧收敛为「先补埋点再定 P0」的共识", messageIds: ["p7"] },
  ],
  toProbe: [
    "导出功能在不同渠道场景的频率差异",
    "批量标签是否与现有运营流程重复",
  ],
  nextActions: [
    { label: "回到 PRD 结构与问题定义节点", href: "/path/nodes/prd-structure", type: "node" },
    { label: "加入复习：优先级判断", href: "/review", type: "review" },
  ],
  confidenceNote: "基于本次 7 轮模拟对话与场景 Rubric 生成；为学习建议，不是能力认证。",
  generatedAt: daysAgo(0),
  providerLabel: "AI 整理（演示）· DeepSeek",
};

export const SCENARIO_SESSION_DONE: ScenarioSession = {
  id: "sc-session-priority-01",
  scenarioId: "scenario-priority",
  status: "completed",
  round: 7,
  maxRounds: 8,
  messages: [
    { id: "sp1", role: "ai", content: "排期只能做两个需求，你们每个都说是 P0，那按什么标准砍？", turnIndex: 1, createdAt: daysAgo(2), status: "sent" },
    { id: "sp2", role: "user", content: "我先按影响和成本给一个口径：影响看受影响用户数与频率，成本看开发与维护。", turnIndex: 2, createdAt: daysAgo(2), status: "sent" },
    { id: "sp3", role: "ai", content: "那你认为导出筛选结果影响最大？有数据吗？", turnIndex: 2, createdAt: daysAgo(2), status: "sent" },
    { id: "sp4", role: "user", content: "周报场景高频，但当前没有导出埋点，这是假设。所以我会先加埋点验证基线。", turnIndex: 3, createdAt: daysAgo(2), status: "sent" },
    { id: "sp5", role: "ai", content: "如果验证结果不支持，你们会怎么回退？", turnIndex: 3, createdAt: daysAgo(2), status: "sent" },
    { id: "sp6", role: "user", content: "回退到批量标签或深色模式二选一，并在两周后复盘埋点数据。", turnIndex: 4, createdAt: daysAgo(2), status: "sent" },
    { id: "sp7", role: "ai", content: "明白，我们达成共识：先补导出埋点，两周后按数据定 P0。可以结束复盘了。", turnIndex: 5, createdAt: daysAgo(2), status: "sent" },
  ],
  startedAt: daysAgo(2),
  updatedAt: daysAgo(2),
  draft: "",
  rubricScores: { clarity: 4, evidence: 3, boundary: 4 },
  report: SCENARIO_REPORT,
};

export const SCENARIO_SESSION_ACTIVE: ScenarioSession = {
  id: "sc-session-renewal-01",
  scenarioId: "scenario-renewal",
  status: "in_progress",
  round: 3,
  maxRounds: 8,
  messages: [
    { id: "sr1", role: "ai", content: "续费这周又降了 8%，你们今天能给方案吗？团队已经让先做续费弹窗了。", turnIndex: 1, createdAt: daysAgo(0), status: "sent" },
    { id: "sr2", role: "user", content: "在下方案前，我想先确认三个信息：退订页有没有埋点、续费下降出现在哪个环节、以及用户真实到期行为。", turnIndex: 2, createdAt: daysAgo(0), status: "sent" },
    { id: "sr3", role: "ai", content: "退订页目前没有埋点。那你怎么判断是弹窗能解决的问题？", turnIndex: 2, createdAt: daysAgo(0), status: "sent" },
  ],
  startedAt: daysAgo(0),
  updatedAt: daysAgo(0),
  draft: "",
};

/* ---------------- 技能雷达 ---------------- */

export const SKILL_DIMENSIONS: SkillDimension[] = [
  {
    id: "comp-product-mindset",
    name: "产品思维与角色认知",
    level: "已有基础",
    evidenceCount: 3,
    confidence: "high",
    evidences: [
      { sourceType: "费曼练习", claim: "区分方案与问题的表述", sourceId: "session-done-prev2", createdAt: daysAgo(3) },
      { sourceType: "完成节点", claim: "产品思维：问题先于方案", sourceId: "pm-mindset", createdAt: daysAgo(6) },
    ],
    recommendation: { gapType: "补强", nextAction: "进行 10 分钟复习", reason: "核心概念清楚，可做一次间隔复习巩固。" },
  },
  {
    id: "comp-need",
    name: "用户研究与需求分析",
    level: "学习中",
    evidenceCount: 4,
    confidence: "medium",
    evidences: [
      { sourceType: "费曼练习", claim: "区分表象诉求与底层任务", sourceId: "session-done-01", createdAt: daysAgo(0) },
      { sourceType: "费曼练习", claim: "待补：假设成功标准基线", sourceId: "session-done-01", createdAt: daysAgo(0) },
      { sourceType: "情境练习", claim: "澄清：用户/指标基线/约束", sourceId: "sc-session-renewal-01", createdAt: daysAgo(1) },
    ],
    recommendation: { gapType: "优先补强", nextAction: "重写一条可验证需求假设", reason: "2 次练习均遗漏成功指标基线。" },
  },
  {
    id: "comp-solution",
    name: "方案与信息架构",
    level: "证据不足",
    evidenceCount: 1,
    confidence: "low",
    evidences: [
      { sourceType: "完成节点", claim: "信息架构基础阅读", sourceId: "user-research-basics", createdAt: daysAgo(10) },
    ],
    recommendation: { gapType: "证据不足", nextAction: "继续当前路径下一节点", reason: "仅一条早期证据，不足以形成画像。" },
  },
  {
    id: "comp-prototype",
    name: "原型与用户体验",
    level: "待开始",
    evidenceCount: 0,
    confidence: "low",
    evidences: [],
    recommendation: { gapType: "待开始", nextAction: "进入原型设计章节", reason: "尚未产生原型与体验相关证据。" },
  },
  {
    id: "comp-prd",
    name: "PRD 与协作交付",
    level: "学习中",
    evidenceCount: 2,
    confidence: "medium",
    evidences: [
      { sourceType: "情境练习", claim: "向研发解释优先级（影响×成本）", sourceId: "sc-session-priority-01", createdAt: daysAgo(2) },
    ],
    recommendation: { gapType: "补强", nextAction: "补充 PRD 结构练习", reason: "优先级沟通已有证据，PRD 结构尚无。" },
  },
];

/* ---------------- 个人资料库 ---------------- */

export const LIBRARY_ITEMS: LibraryItem[] = [
  {
    id: "lib-01",
    kind: "link",
    title: "《用户研究方法：访谈提纲示例》",
    url: "https://methods.example.org/interview-guide",
    sourceName: "官方/机构",
    tags: ["用户研究", "访谈"],
    linkedNodeIds: ["user-research-basics", "interview-methods"],
    visibility: "private",
    checkedAt: daysAgo(0),
    status: "verified",
    memo: "先明确访谈目标，避免把验证问题问成意见题。",
    licenseNote: "公开机构文章；仅保存链接与摘要。",
  },
  {
    id: "lib-02",
    kind: "file",
    title: "我自己制作的 PRD 评审清单.pdf",
    objectKey: "demo/prd-checklist.pdf",
    sourceName: "个人上传",
    tags: ["PRD", "评审"],
    linkedNodeIds: ["req-review"],
    visibility: "private",
    checkedAt: daysAgo(1),
    status: "verified",
    memo: "评审前逐项核对：背景、目标、验收、风险、影响范围。",
    licenseNote: "本人制作，仅自己可见。",
    size: "128 KB",
  },
  {
    id: "lib-03",
    kind: "link",
    title: "需求假设模板与例子",
    url: "https://example.org/hypothesis-template",
    sourceName: "专业方法博客",
    tags: ["需求分析", "假设"],
    linkedNodeIds: ["need-signal"],
    visibility: "private",
    checkedAt: daysAgo(3),
    status: "pending",
    memo: "补充「用户—场景—动机—验证」写法示例。",
    licenseNote: "公开博客；状态待校验。",
  },
  {
    id: "lib-04",
    kind: "note",
    title: "我的摘记：如何定义成功标准",
    sourceName: "个人摘记",
    tags: ["需求分析"],
    linkedNodeIds: ["need-signal"],
    visibility: "private",
    checkedAt: daysAgo(2),
    status: "verified",
    memo: "成功标准要可观测：当前基线、目标值、测量工具与周期。",
    licenseNote: "个人笔记，仅自己可见。",
  },
];

/* ---------------- 内容运营台 ---------------- */

export const ADMIN_FLAGS: ResourceFlag[] = [
  {
    id: "flag-01",
    resourceId: "res-b1",
    resourceTitle: "用户访谈与需求验证方法（NN/g）",
    url: "https://www.nngroup.com/articles/asking-users-questions/",
    grade: "B",
    reason: "link_unavailable",
    note: "用户反馈打开后返回 404，需要复核。",
    createdAt: daysAgo(1),
    status: "pending",
  },
  {
    id: "flag-02",
    resourceId: "res-c2",
    resourceTitle: "视频：PRD 评审常见翻车现场",
    url: "https://bilibili.example.com/video/prd-review",
    grade: "C",
    reason: "content_irrelevant",
    note: "视频版权信息缺失，需确认来源授权。",
    createdAt: daysAgo(2),
    status: "pending",
  },
  {
    id: "flag-03",
    resourceId: "res-b2",
    resourceTitle: "写好 PRD：结构、标准与验收",
    url: "https://pmthought.example.com/prd-guide",
    grade: "B",
    reason: "paywall",
    note: "疑似加入付费墙，需复核免费访问范围。",
    createdAt: daysAgo(3),
    status: "pending",
  },
];

export const ADMIN_RELEASES: CurriculumRelease[] = [
  {
    id: "rel-01",
    title: "AI 产品经理基础能力路径",
    version: "v1.1",
    status: "pending_review",
    updatedAt: daysAgo(0),
    affectedNewPathEstimate: 240,
  },
  {
    id: "rel-02",
    title: "AI 产品经理基础能力路径",
    version: "v1.0",
    status: "published",
    updatedAt: daysAgo(12),
    affectedNewPathEstimate: 0,
  },
  {
    id: "rel-03",
    title: "用户研究方法补强",
    version: "v1.2",
    status: "draft",
    updatedAt: daysAgo(2),
    affectedNewPathEstimate: 85,
  },
];

export const SOURCE_DOMAIN_RULES: SourceDomainRule[] = [
  { id: "sd-01", domain: "google.com", allowedTypes: ["official_docs", "course"], tier: "A", licensePolicy: "允许按条款跳转引用", checkedAt: daysAgo(0), reviewStatus: "approved" },
  { id: "sd-02", domain: "nngroup.com", allowedTypes: ["article"], tier: "B", licensePolicy: "允许摘要引用，禁止全文再发布", checkedAt: daysAgo(1), reviewStatus: "approved" },
  { id: "sd-03", domain: "podcasts.example.com", allowedTypes: ["podcast"], tier: "C", licensePolicy: "仅跳转收听", checkedAt: daysAgo(3), reviewStatus: "pending" },
  { id: "sd-04", domain: "textbook.internal", allowedTypes: ["textbook"], tier: "A", licensePolicy: "自有权教材", checkedAt: daysAgo(12), reviewStatus: "approved" },
];
